dependencies {
	testIntegrationCompile group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationCompile group: "io.swagger.core.v3", name: "swagger-models", version: "2.0.6"
	testIntegrationCompile group: "org.skyscreamer", name: "jsonassert", version: "1.2.3"
	testIntegrationCompile project(":apps:batch-engine:batch-engine-api")
	testIntegrationCompile project(":apps:headless:headless-builder:headless-builder-api")
	testIntegrationCompile project(":apps:info:info-api")
	testIntegrationCompile project(":apps:object:object-api")
	testIntegrationCompile project(":apps:portal-vulcan:portal-vulcan-api")
	testIntegrationCompile project(":test:arquillian-extension-junit-bridge")
}