/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.exportimport.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ImportReportEntry service. Represents a row in the &quot;ImportReportEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.exportimport.model.impl.ImportReportEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.exportimport.model.impl.ImportReportEntryImpl</code>.
 * </p>
 *
 * @author Carlos Correa
 * @see ImportReportEntry
 * @generated
 */
@ProviderType
public interface ImportReportEntryModel
	extends AttachedModel, BaseModel<ImportReportEntry>, MVCCModel,
			ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a import report entry model instance should use the {@link ImportReportEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this import report entry.
	 *
	 * @return the primary key of this import report entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this import report entry.
	 *
	 * @param primaryKey the primary key of this import report entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this import report entry.
	 *
	 * @return the mvcc version of this import report entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this import report entry.
	 *
	 * @param mvccVersion the mvcc version of this import report entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the import report entry ID of this import report entry.
	 *
	 * @return the import report entry ID of this import report entry
	 */
	public long getImportReportEntryId();

	/**
	 * Sets the import report entry ID of this import report entry.
	 *
	 * @param importReportEntryId the import report entry ID of this import report entry
	 */
	public void setImportReportEntryId(long importReportEntryId);

	/**
	 * Returns the company ID of this import report entry.
	 *
	 * @return the company ID of this import report entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this import report entry.
	 *
	 * @param companyId the company ID of this import report entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this import report entry.
	 *
	 * @return the create date of this import report entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this import report entry.
	 *
	 * @param createDate the create date of this import report entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this import report entry.
	 *
	 * @return the modified date of this import report entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this import report entry.
	 *
	 * @param modifiedDate the modified date of this import report entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this import report entry.
	 *
	 * @return the fully qualified class name of this import report entry
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this import report entry.
	 *
	 * @return the class name ID of this import report entry
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this import report entry.
	 *
	 * @param classNameId the class name ID of this import report entry
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this import report entry.
	 *
	 * @return the class pk of this import report entry
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this import report entry.
	 *
	 * @param classPK the class pk of this import report entry
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the entity class name ID of this import report entry.
	 *
	 * @return the entity class name ID of this import report entry
	 */
	public long getEntityClassNameId();

	/**
	 * Sets the entity class name ID of this import report entry.
	 *
	 * @param entityClassNameId the entity class name ID of this import report entry
	 */
	public void setEntityClassNameId(long entityClassNameId);

	/**
	 * Returns the entity external reference code of this import report entry.
	 *
	 * @return the entity external reference code of this import report entry
	 */
	@AutoEscape
	public String getEntityExternalReferenceCode();

	/**
	 * Sets the entity external reference code of this import report entry.
	 *
	 * @param entityExternalReferenceCode the entity external reference code of this import report entry
	 */
	public void setEntityExternalReferenceCode(
		String entityExternalReferenceCode);

	/**
	 * Returns the error of this import report entry.
	 *
	 * @return the error of this import report entry
	 */
	@AutoEscape
	public String getError();

	/**
	 * Sets the error of this import report entry.
	 *
	 * @param error the error of this import report entry
	 */
	public void setError(String error);

	/**
	 * Returns the resolved of this import report entry.
	 *
	 * @return the resolved of this import report entry
	 */
	public boolean getResolved();

	/**
	 * Returns <code>true</code> if this import report entry is resolved.
	 *
	 * @return <code>true</code> if this import report entry is resolved; <code>false</code> otherwise
	 */
	public boolean isResolved();

	/**
	 * Sets whether this import report entry is resolved.
	 *
	 * @param resolved the resolved of this import report entry
	 */
	public void setResolved(boolean resolved);

	/**
	 * Returns the type of this import report entry.
	 *
	 * @return the type of this import report entry
	 */
	public int getType();

	/**
	 * Sets the type of this import report entry.
	 *
	 * @param type the type of this import report entry
	 */
	public void setType(int type);

	@Override
	public ImportReportEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}