/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.exportimport.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.model.ImportReportEntry;
import com.liferay.exportimport.model.ImportReportEntryModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ImportReportEntry service. Represents a row in the &quot;ImportReportEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ImportReportEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ImportReportEntryImpl}.
 * </p>
 *
 * @author Carlos Correa
 * @see ImportReportEntryImpl
 * @generated
 */
public class ImportReportEntryModelImpl
	extends BaseModelImpl<ImportReportEntry> implements ImportReportEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a import report entry model instance should use the <code>ImportReportEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "ImportReportEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"importReportEntryId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"classNameId", Types.BIGINT},
		{"classPK", Types.BIGINT}, {"entityClassNameId", Types.BIGINT},
		{"entityExternalReferenceCode", Types.VARCHAR}, {"error", Types.CLOB},
		{"resolved", Types.BOOLEAN}, {"type_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("importReportEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityClassNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityExternalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("error", Types.CLOB);
		TABLE_COLUMNS_MAP.put("resolved", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ImportReportEntry (mvccVersion LONG default 0 not null,importReportEntryId LONG not null primary key,companyId LONG,createDate DATE null,modifiedDate DATE null,classNameId LONG,classPK LONG,entityClassNameId LONG,entityExternalReferenceCode VARCHAR(75) null,error TEXT null,resolved BOOLEAN,type_ INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table ImportReportEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY importReportEntry.importReportEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ImportReportEntry.importReportEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSPK_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IMPORTREPORTENTRYID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ImportReportEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _importReportEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setImportReportEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _importReportEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ImportReportEntry.class;
	}

	@Override
	public String getModelClassName() {
		return ImportReportEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ImportReportEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ImportReportEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ImportReportEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ImportReportEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ImportReportEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ImportReportEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ImportReportEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ImportReportEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ImportReportEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ImportReportEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ImportReportEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ImportReportEntry, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", ImportReportEntry::getMvccVersion);
			attributeGetterFunctions.put(
				"importReportEntryId",
				ImportReportEntry::getImportReportEntryId);
			attributeGetterFunctions.put(
				"companyId", ImportReportEntry::getCompanyId);
			attributeGetterFunctions.put(
				"createDate", ImportReportEntry::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", ImportReportEntry::getModifiedDate);
			attributeGetterFunctions.put(
				"classNameId", ImportReportEntry::getClassNameId);
			attributeGetterFunctions.put(
				"classPK", ImportReportEntry::getClassPK);
			attributeGetterFunctions.put(
				"entityClassNameId", ImportReportEntry::getEntityClassNameId);
			attributeGetterFunctions.put(
				"entityExternalReferenceCode",
				ImportReportEntry::getEntityExternalReferenceCode);
			attributeGetterFunctions.put("error", ImportReportEntry::getError);
			attributeGetterFunctions.put(
				"resolved", ImportReportEntry::getResolved);
			attributeGetterFunctions.put("type", ImportReportEntry::getType);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ImportReportEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ImportReportEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<ImportReportEntry, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<ImportReportEntry, Long>)
					ImportReportEntry::setMvccVersion);
			attributeSetterBiConsumers.put(
				"importReportEntryId",
				(BiConsumer<ImportReportEntry, Long>)
					ImportReportEntry::setImportReportEntryId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ImportReportEntry, Long>)
					ImportReportEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<ImportReportEntry, Date>)
					ImportReportEntry::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<ImportReportEntry, Date>)
					ImportReportEntry::setModifiedDate);
			attributeSetterBiConsumers.put(
				"classNameId",
				(BiConsumer<ImportReportEntry, Long>)
					ImportReportEntry::setClassNameId);
			attributeSetterBiConsumers.put(
				"classPK",
				(BiConsumer<ImportReportEntry, Long>)
					ImportReportEntry::setClassPK);
			attributeSetterBiConsumers.put(
				"entityClassNameId",
				(BiConsumer<ImportReportEntry, Long>)
					ImportReportEntry::setEntityClassNameId);
			attributeSetterBiConsumers.put(
				"entityExternalReferenceCode",
				(BiConsumer<ImportReportEntry, String>)
					ImportReportEntry::setEntityExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"error",
				(BiConsumer<ImportReportEntry, String>)
					ImportReportEntry::setError);
			attributeSetterBiConsumers.put(
				"resolved",
				(BiConsumer<ImportReportEntry, Boolean>)
					ImportReportEntry::setResolved);
			attributeSetterBiConsumers.put(
				"type",
				(BiConsumer<ImportReportEntry, Integer>)
					ImportReportEntry::setType);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getImportReportEntryId() {
		return _importReportEntryId;
	}

	@Override
	public void setImportReportEntryId(long importReportEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_importReportEntryId = importReportEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classNameId = classNameId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassNameId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("classNameId"));
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classPK = classPK;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassPK() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("classPK"));
	}

	@Override
	public long getEntityClassNameId() {
		return _entityClassNameId;
	}

	@Override
	public void setEntityClassNameId(long entityClassNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityClassNameId = entityClassNameId;
	}

	@Override
	public String getEntityExternalReferenceCode() {
		if (_entityExternalReferenceCode == null) {
			return "";
		}
		else {
			return _entityExternalReferenceCode;
		}
	}

	@Override
	public void setEntityExternalReferenceCode(
		String entityExternalReferenceCode) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityExternalReferenceCode = entityExternalReferenceCode;
	}

	@Override
	public String getError() {
		if (_error == null) {
			return "";
		}
		else {
			return _error;
		}
	}

	@Override
	public void setError(String error) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_error = error;
	}

	@Override
	public boolean getResolved() {
		return _resolved;
	}

	@Override
	public boolean isResolved() {
		return _resolved;
	}

	@Override
	public void setResolved(boolean resolved) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_resolved = resolved;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ImportReportEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ImportReportEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ImportReportEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ImportReportEntryImpl importReportEntryImpl =
			new ImportReportEntryImpl();

		importReportEntryImpl.setMvccVersion(getMvccVersion());
		importReportEntryImpl.setImportReportEntryId(getImportReportEntryId());
		importReportEntryImpl.setCompanyId(getCompanyId());
		importReportEntryImpl.setCreateDate(getCreateDate());
		importReportEntryImpl.setModifiedDate(getModifiedDate());
		importReportEntryImpl.setClassNameId(getClassNameId());
		importReportEntryImpl.setClassPK(getClassPK());
		importReportEntryImpl.setEntityClassNameId(getEntityClassNameId());
		importReportEntryImpl.setEntityExternalReferenceCode(
			getEntityExternalReferenceCode());
		importReportEntryImpl.setError(getError());
		importReportEntryImpl.setResolved(isResolved());
		importReportEntryImpl.setType(getType());

		importReportEntryImpl.resetOriginalValues();

		return importReportEntryImpl;
	}

	@Override
	public ImportReportEntry cloneWithOriginalValues() {
		ImportReportEntryImpl importReportEntryImpl =
			new ImportReportEntryImpl();

		importReportEntryImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		importReportEntryImpl.setImportReportEntryId(
			this.<Long>getColumnOriginalValue("importReportEntryId"));
		importReportEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		importReportEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		importReportEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		importReportEntryImpl.setClassNameId(
			this.<Long>getColumnOriginalValue("classNameId"));
		importReportEntryImpl.setClassPK(
			this.<Long>getColumnOriginalValue("classPK"));
		importReportEntryImpl.setEntityClassNameId(
			this.<Long>getColumnOriginalValue("entityClassNameId"));
		importReportEntryImpl.setEntityExternalReferenceCode(
			this.<String>getColumnOriginalValue("entityExternalReferenceCode"));
		importReportEntryImpl.setError(
			this.<String>getColumnOriginalValue("error"));
		importReportEntryImpl.setResolved(
			this.<Boolean>getColumnOriginalValue("resolved"));
		importReportEntryImpl.setType(
			this.<Integer>getColumnOriginalValue("type_"));

		return importReportEntryImpl;
	}

	@Override
	public int compareTo(ImportReportEntry importReportEntry) {
		long primaryKey = importReportEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ImportReportEntry)) {
			return false;
		}

		ImportReportEntry importReportEntry = (ImportReportEntry)object;

		long primaryKey = importReportEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ImportReportEntry> toCacheModel() {
		ImportReportEntryCacheModel importReportEntryCacheModel =
			new ImportReportEntryCacheModel();

		importReportEntryCacheModel.mvccVersion = getMvccVersion();

		importReportEntryCacheModel.importReportEntryId =
			getImportReportEntryId();

		importReportEntryCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			importReportEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			importReportEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			importReportEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			importReportEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		importReportEntryCacheModel.classNameId = getClassNameId();

		importReportEntryCacheModel.classPK = getClassPK();

		importReportEntryCacheModel.entityClassNameId = getEntityClassNameId();

		importReportEntryCacheModel.entityExternalReferenceCode =
			getEntityExternalReferenceCode();

		String entityExternalReferenceCode =
			importReportEntryCacheModel.entityExternalReferenceCode;

		if ((entityExternalReferenceCode != null) &&
			(entityExternalReferenceCode.length() == 0)) {

			importReportEntryCacheModel.entityExternalReferenceCode = null;
		}

		importReportEntryCacheModel.error = getError();

		String error = importReportEntryCacheModel.error;

		if ((error != null) && (error.length() == 0)) {
			importReportEntryCacheModel.error = null;
		}

		importReportEntryCacheModel.resolved = isResolved();

		importReportEntryCacheModel.type = getType();

		return importReportEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ImportReportEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ImportReportEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ImportReportEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ImportReportEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ImportReportEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ImportReportEntry.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _importReportEntryId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _classNameId;
	private long _classPK;
	private long _entityClassNameId;
	private String _entityExternalReferenceCode;
	private String _error;
	private boolean _resolved;
	private int _type;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ImportReportEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ImportReportEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("importReportEntryId", _importReportEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("classNameId", _classNameId);
		_columnOriginalValues.put("classPK", _classPK);
		_columnOriginalValues.put("entityClassNameId", _entityClassNameId);
		_columnOriginalValues.put(
			"entityExternalReferenceCode", _entityExternalReferenceCode);
		_columnOriginalValues.put("error", _error);
		_columnOriginalValues.put("resolved", _resolved);
		_columnOriginalValues.put("type_", _type);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("importReportEntryId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("createDate", 8L);

		columnBitmasks.put("modifiedDate", 16L);

		columnBitmasks.put("classNameId", 32L);

		columnBitmasks.put("classPK", 64L);

		columnBitmasks.put("entityClassNameId", 128L);

		columnBitmasks.put("entityExternalReferenceCode", 256L);

		columnBitmasks.put("error", 512L);

		columnBitmasks.put("resolved", 1024L);

		columnBitmasks.put("type_", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ImportReportEntry _escapedModel;

}