/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.exportimport.model.impl;

import com.liferay.exportimport.model.ImportReportEntry;
import com.liferay.exportimport.service.ImportReportEntryLocalServiceUtil;

/**
 * The extended model base implementation for the ImportReportEntry service. Represents a row in the &quot;ImportReportEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ImportReportEntryImpl}.
 * </p>
 *
 * @author Carlos Correa
 * @see ImportReportEntryImpl
 * @see ImportReportEntry
 * @generated
 */
public abstract class ImportReportEntryBaseImpl
	extends ImportReportEntryModelImpl implements ImportReportEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a import report entry model instance should use the <code>ImportReportEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ImportReportEntryLocalServiceUtil.addImportReportEntry(this);
		}
		else {
			ImportReportEntryLocalServiceUtil.updateImportReportEntry(this);
		}
	}

}