apiDir: "../object-rest-api/src/main/java"
apiPackagePath: "com.liferay.object.rest"
author: "Javier Gamarra"
forcePredictableOperationId: true
generateBatch: true
generateExportBatch: true
generateOpenAPI: false